apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: gcr.io/recqa-proficeo-dev/user-service@sha256:c423224eb6dd4a10e8140708ac66584cd299cb2480ded4f57f5828b6d6742b69
        imagePullPolicy: "Always"
        env:
          - name: TCP_HOST
            value: '0.0.0.0'
          - name: TCP_PORT
            value: '80'